"""vNext PR 20 gate tests — public surface + 2.0-alpha release."""

from __future__ import annotations

import json
import re
from pathlib import Path

from shiroe.registry import generate_all

REPO_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# Version consistency across all surfaces
# ---------------------------------------------------------------------------

EXPECTED_VERSION = (REPO_ROOT / "shiroe" / "VERSION").read_text(encoding="utf-8").strip()


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_shiroe_version_file() -> None:
    # The other version tests compare their surface against EXPECTED_VERSION,
    # which is read from this file — so this one cannot also compare against
    # it without becoming a tautology. It asserts the canonical file's own
    # contract instead: present, and parseable as SemVer.
    assert EXPECTED_VERSION, "shiroe/VERSION is empty"
    assert re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][\w.\-]+)?", EXPECTED_VERSION), (
        f"shiroe/VERSION is not SemVer: {EXPECTED_VERSION!r}"
    )


def test_pyproject_version() -> None:
    text = _read(REPO_ROOT / "pyproject.toml")
    assert f'version = "{EXPECTED_VERSION}"' in text


def test_plugin_manifest_version() -> None:
    manifest = json.loads(_read(REPO_ROOT / ".claude-plugin" / "plugin.json"))
    assert manifest["version"] == EXPECTED_VERSION


# ---------------------------------------------------------------------------
# Generated registry — regenerated in-place must be deterministic
# ---------------------------------------------------------------------------

REGISTRY_FILES = (
    "components.json", "missions.json", "adapters.json",
    "codecs.json", "capabilities.json",
)


def test_generate_all_writes_registry_files(tmp_path: Path) -> None:
    # Seed missions + policies dirs for the missions registry to load.
    import shutil
    for name in ("missions", "policies"):
        shutil.copytree(REPO_ROOT / name, tmp_path / name)
    written = generate_all(tmp_path)
    names = {p.name for p in written}
    assert names == set(REGISTRY_FILES)


def test_generated_files_present_in_repo() -> None:
    for name in REGISTRY_FILES:
        assert (REPO_ROOT / "registry" / name).exists(), (
            f"registry/{name} missing — run `python3 -c 'from shiroe.registry "
            f"import generate_all; generate_all(\".\")'`"
        )


def test_generated_files_carry_generated_marker() -> None:
    for name in REGISTRY_FILES:
        data = json.loads(_read(REPO_ROOT / "registry" / name))
        assert data.get("$comment", "").startswith("GENERATED BY SHIROE"), (
            f"registry/{name} lacks $comment marker"
        )
        assert data.get("schema"), f"registry/{name} lacks schema"


def test_generated_components_schema_shape() -> None:
    data = json.loads(_read(REPO_ROOT / "registry" / "components.json"))
    ids = {c["id"] for c in data["components"]}
    for expected in ("shiroe.storage", "shiroe.policy", "shiroe.capabilities",
                     "shiroe.runtime", "shiroe.teams", "shiroe.codecs",
                     "shiroe.evidence"):
        assert expected in ids
    for row in data["components"]:
        assert row["status"] in ("runtime", "adapter", "contract",
                                 "experimental")


def test_generated_missions_covers_all_six() -> None:
    data = json.loads(_read(REPO_ROOT / "registry" / "missions.json"))
    ids = {m["id"] for m in data["missions"]}
    assert ids == {"solo", "build", "research", "red", "audit", "ship"}


def test_generated_adapters_reports_all_harnesses() -> None:
    data = json.loads(_read(REPO_ROOT / "registry" / "adapters.json"))
    harness_names = {h["name"] for h in data["harness_adapters"]}
    for expected in ("codex", "claude-code", "gemini-cli", "kimi-code",
                     "hermes", "odysseus", "grok"):
        assert expected in harness_names


# ---------------------------------------------------------------------------
# No unsupported runtime claims (§20 PR-20 gate)
# ---------------------------------------------------------------------------

def test_readme_makes_no_hardcoded_provider_claims() -> None:
    text = _read(REPO_ROOT / "README.md")
    banned = re.compile(
        r"claude-(?:opus|sonnet|haiku|fable|instant)"
        r"|gpt-[0-9]|gemini-[0-9]|codex-gpt"
    )
    # README may reference reasoning classes and harness names, but not
    # provider *model* ids.
    match = banned.search(text)
    assert not match, (
        f"README references provider model id {match.group(0)!r}; "
        f"provider ids belong under shiroe/adapters/providers/"
    )
