"""Generated registry surface (vNext PR 20, master plan §19.3).

Registry files under ``registry/`` are the single source of truth for
README, wiki, CLI help, and release notes. They are generated by
:func:`generate_all` from the runtime code — no hand edits.
"""

from shiroe.registry.generator import (
    RegistryGenerationError,
    generate_all,
    generate_components,
    generate_adapters,
    generate_codecs,
    generate_capabilities,
)

__all__ = [
    "RegistryGenerationError",
    "generate_all", "generate_components",
    "generate_adapters", "generate_codecs",
    "generate_capabilities",
]
