"""Generate ``registry/*.json`` from the runtime code (vNext §19.3).

Every file starts with a machine-readable banner + timestamp.  Downstream
consumers (README, wiki, CLI help, release notes) read from these files;
if they diverge from generated output, CI fails.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

BANNER = (
    "// GENERATED BY SHIROE (shiroe.registry). "
    "SOURCE: runtime code. DO NOT EDIT DIRECTLY.\n"
)


class RegistryGenerationError(RuntimeError):
    pass


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _write(target: Path, payload: dict) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    # JSON with a leading //-banner is not strictly valid JSON, so we
    # emit the banner as a top-level "$comment" field instead.
    payload["$comment"] = BANNER.strip("\n/ ")
    payload["$generated_at"] = _now()
    target.write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
    )
    return target


# ---------------------------------------------------------------------------
# Per-domain generators
# ---------------------------------------------------------------------------

def generate_components(root: Path) -> Path:
    """Runtime / adapter / contract / experimental status per module."""
    from shiroe.core.reasoning import REASONING_CLASSES  # type: ignore  # noqa
    components = [
        {"id": "shiroe.storage",      "status": "runtime",     "purpose": "canonical SQLite v2 + hash-chained JSONL"},
        {"id": "shiroe.policy",       "status": "runtime",     "purpose": "policy precedence + autonomy modes"},
        {"id": "shiroe.capabilities", "status": "runtime",     "purpose": "manifest + lifecycle + gate"},
        {"id": "shiroe.adapters.capabilities", "status": "runtime", "purpose": "capability adapters (skill/agent/cli/mcp/repo)"},
        {"id": "shiroe.missions",     "status": "runtime",     "purpose": "mission blueprint loader"},
        {"id": "shiroe.execution_policies", "status": "runtime", "purpose": "execution policy loader"},
        {"id": "shiroe.teams",        "status": "runtime",     "purpose": "team compiler + resolver"},
        {"id": "shiroe.runtime",      "status": "runtime",     "purpose": "supervisor + state machines"},
        {"id": "shiroe.codecs",       "status": "runtime",     "purpose": "codec registry + selector"},
        {"id": "shiroe.context",      "status": "runtime",     "purpose": "6-section context packet"},
        {"id": "shiroe.evidence",     "status": "runtime",     "purpose": "quality vs robustness"},
        {"id": "shiroe.adapters.harnesses", "status": "adapter", "purpose": "codex/claude/gemini/kimi/hermes/odysseus"},
        {"id": "shiroe.adapters.providers", "status": "adapter", "purpose": "anthropic/openai/xai config"},
        {"id": "shiroe.benchmark.program", "status": "runtime", "purpose": "benchmark registry + §16.10 artifacts"},
    ]
    return _write(root / "registry" / "components.json",
                  {"schema": "shiroe.registry-components/v1",
                   "components": components})


def generate_missions(root: Path) -> Path:
    from shiroe.missions import load_all
    missions = load_all(root)
    payload = {
        "schema": "shiroe.registry-missions/v1",
        "missions": [
            {"id": m.id, "version": m.version,
             "seats": [s["id"] for s in m.required_seats],
             "outputs": m.required_outputs}
            for m in missions
        ],
    }
    return _write(root / "registry" / "missions.json", payload)


def generate_adapters(root: Path) -> Path:
    from shiroe.adapters.harnesses import detect_all
    from shiroe.adapters.capabilities import list_adapters
    payload = {
        "schema": "shiroe.registry-adapters/v1",
        "harness_adapters": [
            {"name": r.name, "enforcement_level": r.enforcement_level.value,
             "supported_features": list(r.supported_features)}
            for r in detect_all()
        ],
        "capability_adapters": list_adapters(),
    }
    return _write(root / "registry" / "adapters.json", payload)


def generate_codecs(root: Path) -> Path:
    from shiroe.codecs import list_codecs
    return _write(root / "registry" / "codecs.json",
                  {"schema": "shiroe.registry-codecs/v1",
                   "codecs": list_codecs()})


def generate_capabilities(root: Path) -> Path:
    from shiroe.capabilities.store import CapabilityStore
    store = CapabilityStore(root)
    try:
        rows = store.list()
    finally:
        store.close()
    # Surface digest + lifecycle_state on every entry so registry consumers
    # (readme, wiki, CLI, snapshot tests) can see when a capability is
    # revoked or drifted without opening the SQLite store.
    for row in rows:
        row["digest"] = row.get("current_digest")
        row["lifecycle_state"] = row.get("lifecycle")
    return _write(root / "registry" / "capabilities.json",
                  {"schema": "shiroe.registry-capabilities/v1",
                   "capabilities": rows})


def generate_all(root: Path | str) -> list[Path]:
    root = Path(root)
    return [
        generate_components(root),
        generate_missions(root),
        generate_adapters(root),
        generate_codecs(root),
        generate_capabilities(root),
    ]
